### PR TITLE
responsiveDropdown option added

### PR DESCRIPTION
**Pull request by escanxr**
Hi,

This code refers to #57 and #22 issues.
I added the `responsiveDropdown` option as it is referred into the readme. The option is false by default, unless if the window's width is smaller than 768px (based on Bootstrap's small size). This works with multiple `countrySelect` if they have different sizes. The `.country-list` width is set on load then on resize.

This is my first contribution to an open source project and I'm not an expert of Javascript so maybe we'll have to change few things in my code.

Please note that the minified js has not changed

### CODE REVIEW

**Comment by mrmarkfrench** [comment]
So as far as functionality goes, this looks good. Thanks for the contribution!

However, in order to make this actually work for most users, we'll need to minify the JS files into the /build directory, which is where most folks load them from.

If you could please update your pull request with this change, I'd be happy to accept it.

**Comment by escanxr** [comment]
It's OK @mrmarkfrench, I have tested the minified file and everything is OK for me. I let you test also on your side. 👋

**Comment by mrmarkfrench** [comment]
Looks like there's still a conflict. Did you pull down the most recent version before you minified?

**Comment by escanxr** [comment]
Oops, I didn't fetch the upstream, sorry.
Should be good now

**Comment by mrmarkfrench** [comment]
Thanks for the contribution!

**Pull request merged**
