### PR TITLE
Expose as nodejs component & fix dropdown bug & add multiple letter type suggestions

### PR DESCRIPTION
**Pull request by jschneier**
Hi this enables me to `require` this package on the server.

### CODE REVIEW

**Comment by jschneier** [comment]
Without the `e.preventDefault()` my dropdown would always close.

**Comment by jschneier** [comment]
The 3rd commit closes #56.

**Comment by jschneier** [comment]
The 4th commit closes #23

**Comment by mrmarkfrench** [comment]
Thanks for your contribution!

If you'd please re-minify this change to prevent conflicts with updates from other pull requests, we'll get this one merged in and available.

**Comment by mapreal19** [comment]
any updates here?

**Comment by jschneier** [comment]
@mrmarkfrench I have rebuilt this off a rebase, please merge. It applied cleanly when I opened this PR originally.

**Pull request merged**
